pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'f2d6c8b7-12d7-4abc-8fae-6ef40689a649', url: 'https://github.com/PodssilDev/Aplicacion_Monolitica_PEP1']]])
                sh "mvn clean install"
            }
        }
        stage("Test"){
            steps{
                sh "mvn test"
            }
        }
        stage("SonarQube Analysis"){
            steps{
                sh "mvn sonar:sonar"
            }
        }
        stage("Build Docker Image"){
            steps{
                sh "docker build -t johnserrano159/mueblesstgopep1 ."
            }
        }
        stage("Push Docker Image"){
            steps{
                withCredentials([string(credentialsId: 'dockerhub', variable: 'dckpass')]) {
                    sh "docker login -u johnserrano159 -p ${dckpass}"  
                }
                sh "docker push johnserrano159/mueblesstgopep1"
            }
        }
    }
    post{
        always{
            sh "docker logout"
        }
    }
}
